on: [push]

jobs:
  copy-issues:
    runs-on: ubuntu-latest
    name: A job to copy issues by label
    steps:
      - name: Copypasta
        id: copypasta
        uses: jasonmadigan/copy-issues-action@v1.0.10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
