on: [push]

jobs:
  clone-issues:
    permissions: write-all
    runs-on: ubuntu-latest
    name: A job to copy issues by label
    steps:
      - name: Clone Issues
        id: clone-issues
        uses: jasonmadigan/clone-issues-action@v1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labelToCopy: 'template-rc'
          addLabel: 'duplicate'
          labelToIgnore: 'duplicate'
